# Este es un flujo de trabajo básico para construir y desplegar un sitio Astro
name: CI

# Controla cuándo se ejecutará este flujo de trabajo
on:
  push:
    branches: 
      - "main"  # Solo ejecuta este workflow cuando haya push en la rama main
  pull_request:
    branches:
      - "main"  # También en pull requests en main
  workflow_dispatch:  # También permite ejecutarlo manualmente desde la pestaña de Actions

# El flujo de trabajo incluye uno o más jobs
jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza un entorno de Ubuntu

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4  # Usa la versión más reciente
        with:
          node-version: '18'  # Asegúrate de usar la versión de Node.js que necesitas

      # 3. Instalar pnpm o npm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Instalar dependencias
      - name: Install dependencies
        run: pnpm install  # O usa npm install si no usas pnpm

      # 5. Construir el proyecto
      - name: Build the project
        run: pnpm build  # O npm run build si usas npm

      # 6. Subir los archivos generados por la build
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Actualizado a la versión 4
        with:
          name: github-pages
          path: ./dist  # Este es el directorio de salida de tu build en Astro

  deploy:
    runs-on: ubuntu-latest  # Despliega también en Ubuntu
    needs: build  # Este trabajo depende de que el trabajo de build termine primero

    steps:
      # Descargar el artefacto de la build
      - name: Download artifact
        uses: actions/download-artifact@v4  # Usa la versión correcta y actualizada
        with:
          name: github-pages
          path: ./dist

      # Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          folder: ./dist
