name: Deploy Astro Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"  # Ejecución programada todos los días de lunes a viernes a las 2:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js (actualizado a la versión 20.x)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3. Instalar pnpm o npm
      - name: Install pnpm
        run: npm install -g pnpm  # O cambia a npm si usas npm

      # 4. Instalar dependencias
      - name: Install dependencies
        run: pnpm install  # O npm install si no usas pnpm

      # 5. Construir el proyecto
      - name: Build the project
        run: pnpm build  # O npm run build si usas npm

      # 6. Verificar si se generó el directorio dist
      - name: List build directory
        run: ls -la ./dist  # Verifica si los archivos generados están en el directorio dist

      # 7. Subir los archivos generados (artefacto de la build)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist  # Asegúrate de que es el directorio correcto

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write  # Permite escribir en GitHub Pages
      id-token: write  # Se asegura de que el token tenga permiso para manejar el id-token

    steps:
      # Descargar los artefactos generados en la etapa de build
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      # Verificar los archivos descargados
      - name: List downloaded files
        run: ls -la ./dist  # Lista los archivos en el directorio descargado

      # Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          emit_telemetry: false  # Añade esto para evitar advertencias de telemetría
