name: Deploy Astro Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"  # Ejecución programada todos los días de lunes a viernes a las 2:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js (asegúrate de que sea la misma versión que usas localmente)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'  # O la versión que usas localmente

      # 3. Instalar pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Verificar versión de pnpm instalada
      - name: Verify pnpm version
        run: pnpm --version

      # 5. Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      # 6. Verificar dependencias instaladas
      - name: Verify installed dependencies
        run: pnpm list --depth=0  # Lista todas las dependencias instaladas

      # 7. Construir el proyecto con depuración
      - name: Build the project
        run: |
          echo "Iniciando la construcción del proyecto en GitHub Actions"
          pnpm build --verbose || exit 1
          echo "Construcción completada"

      # 8. Verificar si se generó el directorio dist
      - name: List build directory
        run: ls -la ./dist  # Verifica si los archivos generados están en el directorio dist

      # 9. Subir los archivos generados (artefacto de la build)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist  # Asegúrate de que es el directorio correcto

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write  # Permite escribir en GitHub Pages
      id-token: write  # Se asegura de que el token tenga permiso para manejar el id-token

    steps:
      # Descargar los artefactos generados en la etapa de build
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      # Verificar los archivos descargados
      - name: List downloaded files
        run: ls -la ./dist  # Lista los archivos en el directorio descargado

      # Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          emit_telemetry: false  # Añade esto para evitar advertencias de telemetría
